import {test} from 'node:test';
import assert from 'node:assert/strict';
function node(tag){const n={tagName:tag,children:[],listeners:new Map(),attributes:new Map(),value:'',checked:false,disabled:false,hidden:false,textContent:'',parentNode:null};n.append=(...xs)=>{for(const x of xs){x.parentNode=n;n.children.push(x)}};n.replaceChildren=(...xs)=>{n.children=[];n.append(...xs)};n.remove=()=>{if(n.parentNode)n.parentNode.children=n.parentNode.children.filter(x=>x!==n)};n.setAttribute=(k,v)=>n.attributes.set(k,String(v));n.getAttribute=k=>n.attributes.get(k)??null;n.addEventListener=(k,fn)=>{if(!n.listeners.has(k))n.listeners.set(k,[]);n.listeners.get(k).push(fn)};n.emit=k=>{for(const fn of n.listeners.get(k)||[])fn({preventDefault(){}})};n.focus=()=>{};return n}
function find(n,type,id){if(n.getAttribute?.('data-'+type)===id)return n;for(const child of n.children){const got=find(child,type,id);if(got)return got;}return null}
const field=(n,id)=>find(n,'field',id),action=(n,id)=>find(n,'action',id);const flush=async()=>{for(let i=0;i<8;i++)await new Promise(resolve=>setImmediate(resolve))};
async function harness(fn,{failActivate=false}={}){
 const old={document:globalThis.document,fetch:globalThis.fetch};const calls=[];const revision='a'.repeat(64),next='b'.repeat(64);const source={kind:'local',location:'/tmp/package'};
 const entry={id:'sample',current:revision,enabled:false,runtime_state:'installed',versions:[{revision,version:'1',title:'Sample',source,access:['exec'],state_schema:1},{revision:next,version:'2',title:'Sample',source,access:['exec','trusted-ui'],state_schema:1}]};
 globalThis.document={head:node('head'),createElement:node};globalThis.fetch=async(url,options={})=>{calls.push({url,options});let ok=true,payload={packages:[entry]};if(url.startsWith('/api/packages/detail')){const rev=new URL(url,'http://localhost').searchParams.get('revision');payload={revision:rev,source,manifest:{id:'sample',version:rev===revision?'1':'2',title:'Sample',files:[],tools:[],skills:[],presets:[],panels:rev===next?[{id:'panel',entry:'ui.js'}]:[],static:rev===next?['ui.js']:[],state_schema:1},files:[]};}else if(url==='/api/packages/activate'){if(failActivate){ok=false;payload={error:'candidate failed'}}else{entry.current=JSON.parse(options.body).revision;entry.enabled=true;entry.runtime_state='enabled';}}else if(url==='/api/packages/install'){payload={candidate:{revision:next,manifest:{id:'sample'}},packages:[entry]};}return {ok,status:ok?200:409,json:async()=>payload};};
 const module=await import('./panel.js');const target=node('div');module.mount(target,{});try{await flush();await fn({target,calls,entry,revision,next,module});}finally{module.unmount(target);globalThis.document=old.document;globalThis.fetch=old.fetch;}
}
test('包导入只提交来源，不自动启用',async()=>{await harness(async({target,calls})=>{field(target,'source-location').value='/tmp/package';action(target,'install-form').emit('submit');await flush();assert.equal(calls.filter(x=>x.url==='/api/packages/install').length,1);assert.equal(calls.some(x=>x.url==='/api/packages/activate'),false);assert.deepEqual(JSON.parse(calls.find(x=>x.url==='/api/packages/install').options.body),{source:{kind:'local',location:'/tmp/package'}});})});
test('包启用需要审阅确认，同源 UI 代码单独确认',async()=>{await harness(async({target,calls,next})=>{action(target,'review:sample').emit('click');await flush();field(target,'review-version').value=next;field(target,'review-version').emit('change');await flush();assert.equal(action(target,'activate').disabled,true);field(target,'confirm-review').checked=true;field(target,'confirm-review').emit('change');assert.equal(action(target,'activate').disabled,true);field(target,'trust-ui').checked=true;field(target,'trust-ui').emit('change');assert.equal(action(target,'activate').disabled,false);action(target,'activate').emit('click');await flush();const body=JSON.parse(calls.find(x=>x.url==='/api/packages/activate').options.body);assert.equal(body.confirm,true);assert.equal(body.trust_ui,true);assert.equal(body.revision,next);})});
test('候选失败保留旧版本和审阅内容',async()=>{await harness(async({target,calls,entry,revision})=>{action(target,'review:sample').emit('click');await flush();field(target,'confirm-review').checked=true;field(target,'confirm-review').emit('change');action(target,'activate').emit('click');await flush();assert.equal(entry.current,revision);assert.match(field(target,'status').textContent,/candidate failed/);assert.equal(field(target,'review').hidden,false);assert.equal(calls.filter(x=>x.url==='/api/packages/activate').length,1);},{failActivate:true})});

test('包面板关闭取消请求且不让迟到结果复活',async()=>{
 const prior={document:globalThis.document,fetch:globalThis.fetch};let release,signal;globalThis.document={head:node('head'),createElement:node};globalThis.fetch=async(_url,options)=>{signal=options.signal;await new Promise(resolve=>release=resolve);return {ok:true,json:async()=>({packages:[]})}};
 const module=await import('./panel.js');const target=node('div');try{module.mount(target,{});await flush();module.unmount(target);assert.equal(signal.aborted,true);release();await flush();assert.equal(globalThis.document.head.children.length,0);assert.equal(field(target,'review').hidden,true);}finally{module.unmount(target);globalThis.document=prior.document;globalThis.fetch=prior.fetch;}
});
